spring:
  datasource:

    #HEROKU DRIVER NAME:
    #driverClassName: org.postgresql.Driver

    driverClassName: com.mysql.cj.jdbc.Driver

    #HEROKU PROPERTIES :   ->    coming from heroku
    # url: ${JDBC_DATABASE_URL:}
    # username: ${JDBC_DATABASE_USERNAME:}
    # password: ${JDBC_DATABASE_PASSWORD:}


    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/pathfinder_workshop_security?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${MySQL_USERNAME}
    password: ${MySQL_PASSWORD}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  sql:
#    init:
#      mode: always
  jpa:

    #PostgreSQL DIALECT FOR HEROKU
    #database-platform: org.hibernate.dialect.PostgreSQLDialect


    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true
#Cloudinary Properties
#cloudinary:
  #api-key: 
  #api-secret: 
  #cloud-name: 



#HEROKU PORT:    ->    coming from heroku
#server.port: ${PORT:8080}:


#actuator properties :
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
      base-path: "/admin"
  server:
    port: 8081